accelerate launch train_unconditional.py \
  --dataset_name="datasets/nbi_v4/train_diff" \
  --resolution=512 --center_crop --random_flip \
  --output_dir="datasets/nbi_v4/diffusion_output" \
  --train_batch_size=1 \
  --num_epochs=100 \
  --gradient_accumulation_steps=1 \
  --use_ema \
  --learning_rate=1e-4 \
  --lr_warmup_steps=500 \
  --mixed_precision=no \
  --push_to_hub \
  --dataloader_num_workers 16